services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app
    init: true

    environment:
      DOCKER_DEV: "true"

    volumes:
      # Windows와 Mac의 현재 프로젝트 폴더 연결
      - type: bind
        source: .
        target: /app

      # Linux 컨테이너용 node_modules 분리
      - type: volume
        source: blog_node_modules
        target: /app/node_modules

    ports:
      - "4321:4321"

volumes:
  blog_node_modules: