name: "Docker Security Scan"

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # 매일 자정(UTC 기준)에 자동 실행

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Docker 이미지 빌드 (검사용)
      - name: Build Docker image
        run: docker build -t my-blog-image .

      # 2. Trivy로 이미지 취약점 스캔
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-blog-image'
          format: 'table'
          exit-code: '0' # 취약점이 발견되면 빌드 실패 처리 (선택 사항, 보고 안함->0, 보고 후 실패->1)
          severity: 'CRITICAL,HIGH' # 치명적이고 높은 위험만 보고
          ignore-unfixed: true